version: '3.4'

services:
  helloworld2:
    image: helloworld2
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8443:8443
    depends_on:
      - mongo
  mongo:
      image: mongo
      ports:
        - "27017:27017"